version: "3.9"

services:
  
  api:
    build: .
    container_name: api
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app   
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+psycopg2://car_user:car_pass@db:5432/car_report
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    depends_on:
      - db
      - redis
   
  
  mcp:
    build: .
    container_name: mcp
    command: python -u -m app.mcp.server
    ports:
      - "5000:5000"   
    environment:
      DATABASE_URL: postgresql+psycopg2://car_user:car_pass@db:5432/car_report
      BACK4APP_APP_ID: ${BACK4APP_APP_ID}
      BACK4APP_REST_KEY: ${BACK4APP_REST_KEY}
      BACK4APP_URL: ${BACK4APP_URL}
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: test12345
    depends_on:
      - db
      - neo4j

  # Celery Worker
  celery_worker:
    build: .
    container_name: worker
    command: ./scripts/worker.sh
    environment:
      DATABASE_URL: postgresql+psycopg2://car_user:car_pass@db:5432/car_report
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      MCP_SERVER_HOST: mcp
      MCP_SERVER_PORT: 5000
    depends_on:
      - db
      - redis
      - mcp

  # Celery Beat
  celery_beat:
    build: .
    container_name: beat
    command: ./scripts/beat.sh
    environment:
      DATABASE_URL: postgresql+psycopg2://car_user:car_pass@db:5432/car_report
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
    depends_on:
      - db
      - redis
      - mcp

  # Redis 
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"

  # PostgreSQL Database
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: car_user
      POSTGRES_PASSWORD: car_pass
      POSTGRES_DB: car_report
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5
    container_name: neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt driver
    environment:
      NEO4J_AUTH: "neo4j/test12345"
    volumes:
      - neo4j_data:/data
volumes:
  postgres_data:
  neo4j_data:

